# Generated by Django 6.1 on 2026-09-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main title of the project', max_length=200)),
                ('tag', models.CharField(help_text='e.g. #001 // INTERNAL SYSTEMS', max_length=50)),
                ('description', models.TextField(help_text='A brief technical overview of the project')),
                ('tech_stack', models.CharField(help_text='Comma-separated list of tech used (e.g. Python, Django, PostgreSQL)', max_length=255)),
                ('status', models.CharField(choices=[('DEPLOYED', 'Deployed'), ('IN_PROGRESS', 'In Progress'), ('DEPRECATED', 'Deprecated')], default='DEPLOYED', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering field for the frontend display (lower is first)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
