# Generated by Django 6.1 on 2026-09-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, help_text='Upload your profile photo here', null=True, upload_to='profile_photos/')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Settings',
            },
        ),
    ]
