# Generated by Django 6.1 on 2026-09-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Image to display on hover', null=True, upload_to='project_images/'),
        ),
    ]
