# Generated by Django 6.1 on 2026-09-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='products_released',
            field=models.IntegerField(default=2, help_text='Number of products released'),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='projects_completed',
            field=models.IntegerField(default=2, help_text='Number of projects completed'),
        ),
    ]
