# Generated by Django 6.1 on 2026-09-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfoliosettings_products_released_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detailed project description for the dropdown'),
        ),
    ]
