# Generated by Django 6.1 on 2026-09-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
    ]
