# Generated by Django 6.1 on 2026-09-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_contactrequest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='api_service_image',
            field=models.ImageField(blank=True, help_text='Hover image for API Architecture section', null=True, upload_to='service_images/'),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='db_service_image',
            field=models.ImageField(blank=True, help_text='Hover image for Database Topology section', null=True, upload_to='service_images/'),
        ),
    ]
